version: '3.9'

services:
  db:
    image: postgres:16
    container_name: java-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app_net

volumes:
  db_data:

networks:
  app_net:
    driver: bridge
